### ISSUE TITLE
Please build the appimage for 9.0

### ISSUE THREAD

**Issue by marczz** [jerefrer/tibetan-translator#1]
Hi Jeremy, please could you build the 9.0 release.

On Linux the 8.2 AppImage crashes with "FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. "

This is a common error on app build with older version of electron.

**Comment by jerefrer** [comment]
Hey Marc :)

I just ported the app to Tauri, a Rust-based Electron alternative, much lighter and efficient that also supports iOS and Android, though I didn't set it up for mobile just yet.

Check the project's page for download links to the latest release for each platform:
https://jerefrer.github.io/tibetan-translator/

Tell me if it works for you !

**Comment by marczz** [comment]
Thanks a lot Jeremy, I have installed the 9.0 deb package, and it works nicely now.
